---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Tags"
permissions: {}
on:
  release:
    types: [published]

jobs:
  update-tag:
    name: "Update the major tag to ${{ github.ref_name }}"
    #environment:
    #  name: "Release"
    #  url: "https://github.com/marketplace/actions/shellchecker"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "${{ false && github.run_attempt == '1' && github.ref_type == 'tag' && github.ref_name != '' }}"
    concurrency:
      group: "${{ github.repository_id }}-${{ github.workflow }}-tag-update"
      cancel-in-progress: false
    permissions:
      contents: write

    steps:
      - name: "Update the major tag"
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: "${{ github.ref_name }}"

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      attestations: write
      id-token: write
      packages: write
    steps:
    - name: Checking out
      uses: actions/checkout@v5
    - name: Publish
      uses: actions/publish-immutable-action@v0
      #with:
      #  github-token: ${{ secrets.GITHUB_TOKEN }}
